spring:
  application:
    name: kryptos
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptos
    username: cryptos
    password: Test@123
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080
  servlet:
    context-path: /kryptos

slack:
  username: nayakrranjan@gmail.com
  status: true

logging:
  level:
    root: info
